#include <iostream>

#include "jclab_license/license_verifier.h"

int main() {
    jclab_license::LicenseVerifier* verifier = jclab_license::LicenseVerifier::getInstance();

    const std::string license_b64 = "MIIEiwYJKoZIhvcNAQcCoIIEfDCCBHgCAQExDzANBglghkgBZQMEAgEFADCBjwYMKwYBBAGD6RcUi10BoH8EfQi9gvHGsDNSBHRlc3RaD3Rlc3RAamMtbGFiLm5ldKIBDHRlc3QtcHJvZHVjdKgBAbAB79vZ2QbwAdCGA/oBPgoMdGVzdC1wcm9kdWN0EggUB5ydEsjg6RjTogEiIOulKFJEaZnsR7x+sraZeAdMas3cKS0+1Gy2WHMbg3XwoIICsjCCAq4wggI0oAMCAQICFBPEHn+fr8BdYtWTUjbKOliD17LIMAoGCCqGSM49BAMDMCMxITAfBgNVBAMMGEpDLUxhYiBMaWNlbnNlIEF1dGhvcml0eTAeFw0yNTEyMDgwOTUwMjlaFw0yNTEyMzEyMzU5NTlaMEQxJDAiBgNVBAMMG0pDLUxhYiBMaWNlbnNlIFNpZ25pbmcgMjAyNTEPMA0GA1UECgwGSkMtTGFiMQswCQYDVQQGEwJLUjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJOuY9C1WycGg2mTVPe9IYdMl8gTW4uvQ1IxTue6/pW4QdVoqQxw8xn0JaigkHmuABfpmzjnNbn3QC7iwO09id+jggEjMIIBHzAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFJohccxcBXm7kxT67+f+G578WpsHMBcGA1UdJQQQMA4GDCsGAQQBg+kXCgOLXTCBpQYDVR0fBIGdMIGaMIGXoGygaoZoaHR0cDovL2NhLmxpY2Vuc2UuamNsYWIua3IvZWpiY2EvcHVibGljd2ViL3dlYmRpc3QvY2VydGRpc3Q/Y21kPWNybCZpc3N1ZXI9Q04lM0RKQy1MYWIrTGljZW5zZStBdXRob3JpdHmiJ6QlMCMxITAfBgNVBAMMGEpDLUxhYiBMaWNlbnNlIEF1dGhvcml0eTAdBgNVHQ4EFgQUNl64ccfcwBFs+pgQUedce6PvMQEwDgYDVR0PAQH/BAQDAgbAMAoGCCqGSM49BAMDA2gAMGUCMHQ0sgO0FB4+WNxMcBrOlEG/2SCncx4j3I4ab0KQwcV/ECPKOmjJ+z/gOzXKuZEjBQIxAJIHrb7V6NFGDDFAc+pkOkKkFjohGyGs/6tE5pzDIU0dZHRcA8bsva7ghx/rcr/XUzGCARgwggEUAgEBMDswIzEhMB8GA1UEAwwYSkMtTGFiIExpY2Vuc2UgQXV0aG9yaXR5AhQTxB5/n6/AXWLVk1I2yjpYg9eyyDANBglghkgBZQMEAgEFAKBsMBwGCSqGSIb3DQEJBTEPFw0yNTEyMTAxNTIzMzFaMBsGCSqGSIb3DQEJAzEOBgwrBgEEAYPpFxSLXQEwLwYJKoZIhvcNAQkEMSIEIPOXK+YCd08ZwzuyapenyYULqJHPm4r0NW3XOXU6o5OaMAsGByqGSM49AgEFAARIMEYCIQDab+rpeOaPKjWhdhsMCk02VrYDyxoQk2UkSxkiFALk4AIhAKygN3XT2RT7AwkTDobFI38CybvnWSbSAx9nVO2dc9JN";

    auto result = verifier->verifyB64(license_b64);

    if (result.verified) {
        std::cout << "License verified successfully." << std::endl;
    } else {
        std::cout << "License verification failed." << std::endl;
    }

    return 0;
}