// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: jclab_license.proto

package license_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LicenseType int32

const (
	LicenseType_kUnknownLicenseType LicenseType = 0
	LicenseType_kTermMaintenance    LicenseType = 1
	LicenseType_kSubscribe          LicenseType = 2
)

// Enum value maps for LicenseType.
var (
	LicenseType_name = map[int32]string{
		0: "kUnknownLicenseType",
		1: "kTermMaintenance",
		2: "kSubscribe",
	}
	LicenseType_value = map[string]int32{
		"kUnknownLicenseType": 0,
		"kTermMaintenance":    1,
		"kSubscribe":          2,
	}
)

func (x LicenseType) Enum() *LicenseType {
	p := new(LicenseType)
	*p = x
	return p
}

func (x LicenseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LicenseType) Descriptor() protoreflect.EnumDescriptor {
	return file_jclab_license_proto_enumTypes[0].Descriptor()
}

func (LicenseType) Type() protoreflect.EnumType {
	return &file_jclab_license_proto_enumTypes[0]
}

func (x LicenseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LicenseType.Descriptor instead.
func (LicenseType) EnumDescriptor() ([]byte, []int) {
	return file_jclab_license_proto_rawDescGZIP(), []int{0}
}

type TimecenseKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // key_id (8 bytes, 64 bits)
	VersionLimit  int32                  `protobuf:"varint,3,opt,name=version_limit,json=versionLimit,proto3" json:"version_limit,omitempty"`
	Key           []byte                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimecenseKey) Reset() {
	*x = TimecenseKey{}
	mi := &file_jclab_license_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimecenseKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimecenseKey) ProtoMessage() {}

func (x *TimecenseKey) ProtoReflect() protoreflect.Message {
	mi := &file_jclab_license_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimecenseKey.ProtoReflect.Descriptor instead.
func (*TimecenseKey) Descriptor() ([]byte, []int) {
	return file_jclab_license_proto_rawDescGZIP(), []int{0}
}

func (x *TimecenseKey) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *TimecenseKey) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TimecenseKey) GetVersionLimit() int32 {
	if x != nil {
		return x.VersionLimit
	}
	return 0
}

func (x *TimecenseKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LicensePack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unix epoch time as milliseconds
	IssuedAt            int64             `protobuf:"varint,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	LicenseeName        string            `protobuf:"bytes,10,opt,name=licensee_name,json=licenseeName,proto3" json:"licensee_name,omitempty"`
	LicenseeEmail       string            `protobuf:"bytes,11,opt,name=licensee_email,json=licenseeEmail,proto3" json:"licensee_email,omitempty"`
	LicensedProduct     []string          `protobuf:"bytes,20,rep,name=licensed_product,json=licensedProduct,proto3" json:"licensed_product,omitempty"`
	LicenseType         LicenseType       `protobuf:"varint,21,opt,name=license_type,json=licenseType,proto3,enum=kr.jclab.license.proto.LicenseType" json:"license_type,omitempty"`
	LicenseExpireAt     int64             `protobuf:"varint,22,opt,name=license_expire_at,json=licenseExpireAt,proto3" json:"license_expire_at,omitempty"`
	TimecenseMaxVersion int32             `protobuf:"varint,30,opt,name=timecense_max_version,json=timecenseMaxVersion,proto3" json:"timecense_max_version,omitempty"`
	TimecenseKey        []*TimecenseKey   `protobuf:"bytes,31,rep,name=timecense_key,json=timecenseKey,proto3" json:"timecense_key,omitempty"`
	Attribute           map[string][]byte `protobuf:"bytes,100,rep,name=attribute,proto3" json:"attribute,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LicensePack) Reset() {
	*x = LicensePack{}
	mi := &file_jclab_license_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicensePack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicensePack) ProtoMessage() {}

func (x *LicensePack) ProtoReflect() protoreflect.Message {
	mi := &file_jclab_license_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicensePack.ProtoReflect.Descriptor instead.
func (*LicensePack) Descriptor() ([]byte, []int) {
	return file_jclab_license_proto_rawDescGZIP(), []int{1}
}

func (x *LicensePack) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *LicensePack) GetLicenseeName() string {
	if x != nil {
		return x.LicenseeName
	}
	return ""
}

func (x *LicensePack) GetLicenseeEmail() string {
	if x != nil {
		return x.LicenseeEmail
	}
	return ""
}

func (x *LicensePack) GetLicensedProduct() []string {
	if x != nil {
		return x.LicensedProduct
	}
	return nil
}

func (x *LicensePack) GetLicenseType() LicenseType {
	if x != nil {
		return x.LicenseType
	}
	return LicenseType_kUnknownLicenseType
}

func (x *LicensePack) GetLicenseExpireAt() int64 {
	if x != nil {
		return x.LicenseExpireAt
	}
	return 0
}

func (x *LicensePack) GetTimecenseMaxVersion() int32 {
	if x != nil {
		return x.TimecenseMaxVersion
	}
	return 0
}

func (x *LicensePack) GetTimecenseKey() []*TimecenseKey {
	if x != nil {
		return x.TimecenseKey
	}
	return nil
}

func (x *LicensePack) GetAttribute() map[string][]byte {
	if x != nil {
		return x.Attribute
	}
	return nil
}

var File_jclab_license_proto protoreflect.FileDescriptor

const file_jclab_license_proto_rawDesc = "" +
	"\n" +
	"\x13jclab_license.proto\x12\x16kr.jclab.license.proto\"m\n" +
	"\fTimecenseKey\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12#\n" +
	"\rversion_limit\x18\x03 \x01(\x05R\fversionLimit\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\"\xa4\x04\n" +
	"\vLicensePack\x12\x1b\n" +
	"\tissued_at\x18\x01 \x01(\x03R\bissuedAt\x12#\n" +
	"\rlicensee_name\x18\n" +
	" \x01(\tR\flicenseeName\x12%\n" +
	"\x0elicensee_email\x18\v \x01(\tR\rlicenseeEmail\x12)\n" +
	"\x10licensed_product\x18\x14 \x03(\tR\x0flicensedProduct\x12F\n" +
	"\flicense_type\x18\x15 \x01(\x0e2#.kr.jclab.license.proto.LicenseTypeR\vlicenseType\x12*\n" +
	"\x11license_expire_at\x18\x16 \x01(\x03R\x0flicenseExpireAt\x122\n" +
	"\x15timecense_max_version\x18\x1e \x01(\x05R\x13timecenseMaxVersion\x12I\n" +
	"\rtimecense_key\x18\x1f \x03(\v2$.kr.jclab.license.proto.TimecenseKeyR\ftimecenseKey\x12P\n" +
	"\tattribute\x18d \x03(\v22.kr.jclab.license.proto.LicensePack.AttributeEntryR\tattribute\x1a<\n" +
	"\x0eAttributeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01*L\n" +
	"\vLicenseType\x12\x17\n" +
	"\x13kUnknownLicenseType\x10\x00\x12\x14\n" +
	"\x10kTermMaintenance\x10\x01\x12\x0e\n" +
	"\n" +
	"kSubscribe\x10\x02BZ\n" +
	"\x16kr.jclab.license.protoB\fLicenseProtoP\x01Z0github.com/jc-lab/jclab-license-v2/license_protob\x06proto3"

var (
	file_jclab_license_proto_rawDescOnce sync.Once
	file_jclab_license_proto_rawDescData []byte
)

func file_jclab_license_proto_rawDescGZIP() []byte {
	file_jclab_license_proto_rawDescOnce.Do(func() {
		file_jclab_license_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jclab_license_proto_rawDesc), len(file_jclab_license_proto_rawDesc)))
	})
	return file_jclab_license_proto_rawDescData
}

var file_jclab_license_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jclab_license_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jclab_license_proto_goTypes = []any{
	(LicenseType)(0),     // 0: kr.jclab.license.proto.LicenseType
	(*TimecenseKey)(nil), // 1: kr.jclab.license.proto.TimecenseKey
	(*LicensePack)(nil),  // 2: kr.jclab.license.proto.LicensePack
	nil,                  // 3: kr.jclab.license.proto.LicensePack.AttributeEntry
}
var file_jclab_license_proto_depIdxs = []int32{
	0, // 0: kr.jclab.license.proto.LicensePack.license_type:type_name -> kr.jclab.license.proto.LicenseType
	1, // 1: kr.jclab.license.proto.LicensePack.timecense_key:type_name -> kr.jclab.license.proto.TimecenseKey
	3, // 2: kr.jclab.license.proto.LicensePack.attribute:type_name -> kr.jclab.license.proto.LicensePack.AttributeEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jclab_license_proto_init() }
func file_jclab_license_proto_init() {
	if File_jclab_license_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jclab_license_proto_rawDesc), len(file_jclab_license_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jclab_license_proto_goTypes,
		DependencyIndexes: file_jclab_license_proto_depIdxs,
		EnumInfos:         file_jclab_license_proto_enumTypes,
		MessageInfos:      file_jclab_license_proto_msgTypes,
	}.Build()
	File_jclab_license_proto = out.File
	file_jclab_license_proto_goTypes = nil
	file_jclab_license_proto_depIdxs = nil
}
