#!/bin/bash

# This script converts a DER file to a C++ header file.

# The script is located in an arbitrary sub-directory of the project.
# The project root is two levels up.
PROJECT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."

INPUT_FILE="$PROJECT_ROOT_DIR/internal/jclabconstant/jclab_license_authority.der"
OUTPUT_DIR="$PROJECT_ROOT_DIR/include/jclab_license/generated"
OUTPUT_FILE="$OUTPUT_DIR/jclab_license_authority.h"
VAR_NAME="JCLAB_LICENSE_AUTHORITY_DER"

mkdir -p "$OUTPUT_DIR"

echo "// Generated by scripts/generate_cert_header.sh" > "$OUTPUT_FILE"
echo "#ifndef JCLAB_LICENSE_AUTHORITY_H_" >> "$OUTPUT_FILE"
echo "#define JCLAB_LICENSE_AUTHORITY_H_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "#include <cstdint>" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
xxd -i "$INPUT_FILE" | sed "s/unsigned char.*/static const uint8_t ${VAR_NAME}[] = {/" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_INPUT_FILE"
echo "#endif // JCLAB_LICENSE_AUTHORITY_H_" >> "$OUTPUT_FILE"

# Format with clang-format
if command -v clang-format > /dev/null; then
    clang-format -i "$OUTPUT_FILE"
fi
